### ISSUE TITLE
How do I use

### ISSUE THREAD

**Issue by AungThiha** [zdavatz/ydocx#10]
I have installed ydocx gem and I still can't use it.
if I run docx2html form the terminal. It returns command not found.
I also tried to clone this repo and install dependencies using "bundle install". It failed.
Please, add some guide on how to use in ruby.

**Comment by zdavatz** [comment]
It depends on you linux setup. What Linux and what Ruby Version do you use?

**Comment by AungThiha** [comment]
I'm on OS X Mavericks

**Comment by zdavatz** [comment]
Do you use home-brew on your Mac? If not install it first. http://brew.sh
