### ISSUE TITLE
Test for nil needs to come first

### ISSUE THREAD

**Issue by MadBomber** [zdavatz/ydocx#2]
ruby-1.9.3-p429 [dewayne@fc18 0]$ docx2html 10019162.docx 
/home/dewayne/.rvm/gems/ruby-1.9.3-p429/gems/ydocx-1.2.3/lib/ydocx/templates/fachinfo.rb:109:in `parse_title': undefined method `inner_text' for nil:NilClass (NoMethodError)

Change the line to read like this:

         ( node.parent.previous.nil?  or  node.previous.inner_text.strip.empty? )

**Comment by zdavatz** [comment]
Thank you @jhubert and @MadBomber.
